### ISSUE TITLE
landing UI update

### ISSUE THREAD

**Issue by swccho** [shudhuiami/Revealify#26]

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/953c9a8f-3877-41e2-a9de-f5e19ec08913)
remove this section

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/de7e25ea-49e9-4581-b923-920e0bccf4ef)
Remove those

**Comment by noyonredishketch** [comment]
Project theme color: #41e099

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/b94ff8e0-23f8-4dbf-93bc-ee9862b8bbcf)
use one for those image

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/47ae36c6-f10c-4e56-92e1-24fb316371d6)
here

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/be1285ed-e3c2-4803-a2d5-90cfe99144e1)

Welcome to Revealify - Unveil Your Professional Potential

Ready to showcase your skills and experience in style? Welcome to Revealify, where we empower you to create stunning resumes that captivate employers.

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/92f6a369-651d-4d67-a53d-e0cbc6f9ff54)
Why Choose Revealify?

Unleash the power of Revealify to transform your resume into a work of art! With dazzling templates, monthly revelations of new designs, an intuitive interface, and exclusive account benefits, Revealify offers a seamless and stylish resume-building experience. Elevate your professional presence and make a lasting impression with Revealify – where your potential gets the spotlight it deserves.

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/12a802d8-4c6a-4ef7-9f9f-fb90a90247a5)
✨ Dazzling Templates: Explore our curated collection of captivating and sophisticated templates designed to make your resume unforgettable.

🔄 Monthly Revelations: Stay ahead of the curve! We unveil new templates every month to keep your options fresh and on-trend.

🌐 Intuitive Interface: Crafting a professional resume is a breeze with our user-friendly platform. Experience seamless design and hassle-free customization.

🔐 Account Benefits: Elevate your experience by creating an account. Save your resumes and access them anytime, anywhere.

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/dfc45dad-f9b8-4718-8e52-25e4a78be4e3)
Main Features of Revealify

Join Revealify and experience these standout features that set us apart in the world of resume building. Elevate your career journey with a platform designed to reveal your true professional potential.
🌟 Dazzling Templates: Choose from a curated selection of stunning and professionally designed templates that cater to various industries. Make a visual impact with styles that reveal your unique professional personality.

🔄 Monthly Revelations: Stay ahead of the competition with our commitment to constant innovation. Every month, we unveil new templates, ensuring that your resume reflects the latest trends and captures attention.

🌐 Intuitive Interface: Crafting your resume is a breeze with our user-friendly interface. Effortlessly input your details, customize layouts, and preview your changes in real-time. No design skills required – just reveal your best self effortlessly.

🔐 Account Benefits: Unlock a personalized experience by creating a Revealify account. Save multiple resumes, access them from any device, and enjoy exclusive features tailored to enhance your resume-building journey.

🎨 Customization Options: Tailor your resume to perfection with a range of customization options. Adjust colors, fonts, and layouts to match your personal brand. Revealify puts you in control of your professional narrative.

🚀 One-Click Downloads: Transform your masterpiece into a polished PDF with just one click. Download and share your professionally crafted resume seamlessly, ready to impress recruiters and hiring managers.

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/231c8ff6-df74-40a2-8bc4-81572419ede5)
Hide this for now
we will develop real data entry section for this

**Comment by noyonredishketch** [comment]
![image](https://github.com/shudhuiami/Revealify/assets/106644490/9b0968e1-3af2-4a88-b6b9-fb1ae04ba6c4)
